services:
  dyndns:
    build: dyndns
    volumes:
      - ./dyndns/settings.txt:/settings.txt

  redis:
    image: redis:7-alpine
    volumes:
      - redis-vol-1:/data/
    restart: always
    ports:
      - "${REDIS_PORT:-127.0.0.1:7654}:6379"
    sysctls:
      - net.core.somaxconn=4096
    networks:
      mail-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.249
        aliases:
          - redis

  netfilter:
    build:
      context: .
      args:
        PYTHON_EXTRAS: netfilter
      target: netfilter
    depends_on:
      - redis
    stop_grace_period: 30s
    restart: always
    privileged: true
    environment:
      - NETFILTER_CHAIN_NAME=${NETFILTER_CHAIN_NAME:-MAIL}
      - NETFILTER_CHAIN_COMMENT=${NETFILTER_CHAIN_COMMENT:-mail}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
      - SNAT_TO_SOURCE=${SNAT_TO_SOURCE:-}
      - SNAT6_TO_SOURCE=${SNAT6_TO_SOURCE:-}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
    network_mode: "host"
    volumes:
      - /lib/modules:/lib/modules:ro

  unbound:
    build: unbound
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:ro,Z
    restart: always
    networks:
      mail-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.254
        aliases:
          - unbound

  dockerapi:
    build:
      context: .
      args:
        PYTHON_EXTRAS: dockerapi
      target: dockerapi
    security_opt:
      - label=disable
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-taram}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      mail-network:
        aliases:
          - dockerapi

  monit:
    build: monit
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    depends_on:
      - dockerapi
    ports:
      - 2812
    networks:
      mail-network:
        aliases:
          - monit

  ipv6nat:
    image: robbertkl/ipv6nat
    depends_on:
      - unbound
      - monit
      - dockerapi
    security_opt:
      - label=disable
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro

networks:
  mail-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-mail
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}

volumes:
  redis-vol-1:
