services:
  dyndns:
    build: dyndns
    volumes:
      - ./dyndns/settings.txt:/settings.txt

  unbound:
    build: unbound
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:ro,Z
    restart: always
    networks:
      mail-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.254
        aliases:
          - unbound

  dockerapi:
    build:
      context: .
      dockerfile: dockerapi/Dockerfile
    security_opt:
      - label=disable
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      mail-network:
        aliases:
          - dockerapi

networks:
  mail-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-mail
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
