services:
  dyndns:
    build: dyndns
    volumes:
      - ./dyndns/settings.txt:/settings.txt

  unbound:
    build: unbound
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:ro,Z
    restart: always
    networks:
      mail-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.254

  mysql:
    image: mariadb:10.5
    depends_on:
      - unbound
    stop_grace_period: 45s
    volumes:
      - ./mysql/conf.d/:/etc/mysql/conf.d/:ro,Z
      - mysql-vol-1:/var/lib/mysql/
      - mysql-socket-vol-1:/var/run/mysqld/
    environment:
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_INITDB_SKIP_TZINFO=1
    restart: always
    ports:
      - "${SQL_PORT:-127.0.0.1:13306}:3306"
    networks:
      - mail-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis-vol-1:/data/
    restart: always
    ports:
      - "${REDIS_PORT:-127.0.0.1:7654}:6379"
    sysctls:
      - net.core.somaxconn=4096
    networks:
      mail-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.249

  clamd:
    image: clamav/clamav:1.4.1
    restart: always
    depends_on:
      - unbound
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    volumes:
      - ./clamd/clamd.conf:/etc/clamav/clamd.conf:ro,Z
      - ./clamd/freshclam.conf:/etc/clamav/freshclam.conf:ro,Z
      - clamd-vol-1:/var/lib/clamav
    networks:
      - mail-network

  rspamd:
    build: rspamd
    stop_grace_period: 30s
    depends_on:
      - clamd
      - redis
    environment:
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
    volumes:
      - ./rspamd/custom/:/etc/rspamd/custom:z
      - rspamd-vol-1:/var/lib/rspamd
    restart: always
    hostname: rspamd
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      - mail-network

  netfilter:
    build:
      context: .
      args:
        PYTHON_EXTRAS: netfilter
      target: netfilter
    stop_grace_period: 30s
    restart: always
    privileged: true
    environment:
      - NETFILTER_CHAIN_NAME=${NETFILTER_CHAIN_NAME:-MAIL}
      - NETFILTER_CHAIN_COMMENT=${NETFILTER_CHAIN_COMMENT:-mail}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
      - SNAT_TO_SOURCE=${SNAT_TO_SOURCE:-}
      - SNAT6_TO_SOURCE=${SNAT6_TO_SOURCE:-}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
    network_mode: "host"
    volumes:
      - /lib/modules:/lib/modules:ro

  dockerapi:
    build:
      context: .
      args:
        PYTHON_EXTRAS: dockerapi
      target: dockerapi
    security_opt:
      - label=disable
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-taram}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - mail-network

  monit:
    build: monit
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    depends_on:
      - dockerapi
      - mysql
    ports:
      - 2812
    volumes:
      - rspamd-vol-1:/var/lib/rspamd
      - mysql-socket-vol-1:/var/run/mysqld/
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
    networks:
      - mail-network

  ipv6nat:
    image: robbertkl/ipv6nat
    depends_on:
      - clamd
      - dockerapi
      - monit
      - mysql
      - rspamd
      - unbound
    security_opt:
      - label=disable
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro

networks:
  mail-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-mail
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}

volumes:
  clamd-vol-1:
  mysql-vol-1:
  mysql-socket-vol-1:
  redis-vol-1:
  rspamd-vol-1:
