services:
  memcached:
    command: memcached -vv

  frontend:
    build:
      target: dev
    environment:
      NODE_ENV: development

  api:
    command: >
      bash -c "alembic upgrade head
      && uvicorn --host=0.0.0.0 --port=80 taramail.api:app --log-config=/app/log-config.dev.yaml --reload"
    volumes:
      - ./backend/taramail:/app/taramail

  dockerapi:
    command: uvicorn --host=0.0.0.0 --port=80 taramail.dockerapi:app --reload
    environment:
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend/taramail:/app/taramail
